#!/usr/bin/env python3
"""Minimal QWinUI3 Python window (generated by qwinui3 init)."""

from __future__ import annotations

import sys
from pathlib import Path

# Prefer: pip install qwinui3  — or set QWINUI3_ROOT to a shared kit.
ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from PySide6.QtCore import QUrl
from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine

try:
    from qwinui3 import configure_environment, configure_application
except ImportError:
    print("pip install qwinui3 PySide6", file=sys.stderr)
    raise SystemExit(1)

def main() -> int:
    configure_environment()
    app = QGuiApplication(sys.argv)
    configure_application("org.example.myapp")
    engine = QQmlApplicationEngine()
    qml = ROOT / "Main.qml"
    engine.load(QUrl.fromLocalFile(str(qml)))
    if not engine.rootObjects():
        return 1
    return app.exec()

if __name__ == "__main__":
    raise SystemExit(main())
